import { pgTable, text, numeric, timestamp, index } from "drizzle-orm/pg-core";

/**
 * orders — Live / paper order records created by the trading engine.
 *
 * Lifecycle:
 *   PENDING → PARTIALLY_FILLED → FILLED
 *           → CANCELLED
 *           → REJECTED (pre-trade risk check failed)
 *
 * Distinct from the `trades` table which stores SIMULATED analytics trades.
 * These are real (or paper) orders placed by users via the order book.
 * ID is a UUID generated in application code via crypto.randomUUID().
 */
export const ordersTable = pgTable("orders", {
  id:     text("id").primaryKey(),
  userId: text("user_id").notNull(),

  symbol: text("symbol").notNull(),
  side:   text("side").notNull(),   // "BUY" | "SELL"
  type:   text("type").notNull(),   // "MARKET" | "LIMIT" | "STOP_LIMIT"

  /** Limit/stop price — null for MARKET orders. */
  price:    numeric("price"),
  quantity: numeric("quantity").notNull(),

  /** Running fill tracker — updated after each partial or full fill. */
  filledQuantity: numeric("filled_quantity").default("0").notNull(),

  /**
   * "PENDING" | "PARTIALLY_FILLED" | "FILLED" | "CANCELLED" | "REJECTED"
   * All transitions go through recordFill() or cancelOrder() in order-lifecycle.ts.
   */
  status: text("status").notNull(),

  /**
   * "paper" | "live" — paper orders never leave the system.
   * Live orders are forwarded to Binance Futures.
   */
  mode: text("mode").notNull().default("paper"),

  /** Total fee paid for this order (sum of all fill fees). */
  fee:      numeric("fee").default("0").notNull(),
  /** Asset in which the fee was charged (e.g. "USDT", "BNB"). */
  feeAsset: text("fee_asset").default("USDT").notNull(),

  /** Binance order ID returned on live orders — null for paper. */
  exchangeOrderId: text("exchange_order_id"),

  /** Populated when status = "CANCELLED". */
  cancelledAt:   timestamp("cancelled_at",   { withTimezone: true }),
  cancelReason:  text("cancel_reason"),

  /** Populated when status = "REJECTED" (pre-trade check failure reason). */
  rejectReason: text("reject_reason"),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("orders_user_status_idx").on(t.userId, t.status),
  index("orders_user_symbol_idx").on(t.userId, t.symbol),
  index("orders_created_at_idx").on(t.createdAt),
]);

/**
 * trade_executions — Individual fill events generated by the execution engine.
 *
 * One order can produce multiple executions (e.g. partial fills at different prices).
 * Each row records the exact price, quantity, and fee at fill time.
 */
export const tradeExecutionsTable = pgTable("trade_executions", {
  id:      text("id").primaryKey(),
  orderId: text("order_id").notNull().references(() => ordersTable.id, { onDelete: "cascade" }),
  userId:  text("user_id").notNull(),

  /** Side of this specific fill (matches the parent order's side). */
  side: text("side").notNull(),

  price:    numeric("price").notNull(),
  quantity: numeric("quantity").notNull(),

  /** Fee for this individual fill (feeRate × price × quantity). */
  fee:      numeric("fee").default("0").notNull(),
  feeAsset: text("fee_asset").default("USDT").notNull(),

  executedAt: timestamp("executed_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index("executions_order_id_idx").on(t.orderId),
  index("executions_user_id_idx").on(t.userId),
]);

export type Order            = typeof ordersTable.$inferSelect;
export type NewOrder         = typeof ordersTable.$inferInsert;
export type TradeExecution   = typeof tradeExecutionsTable.$inferSelect;
export type NewTradeExecution = typeof tradeExecutionsTable.$inferInsert;
